name: Build and Release ASP.NET Core

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish
        run: dotnet publish AutoServiceAW.API/AutoServiceAW.API.csproj -c Release -o publish

      - name: Zip publish
        run: |
          cd publish
          zip -r ../AutoServiceAW.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: AutoServiceAW.zip