name: Build and Release ASP.NET Core

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore AutoServiceAW.API/AutoServiceAW.API.csproj

      - name: Build
        run: dotnet build AutoServiceAW.API/AutoServiceAW.API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish AutoServiceAW.API/AutoServiceAW.API.csproj --configuration Release --no-build --output publish

      - name: Compress Publish Folder
        run: |
          cd publish
          zip -r ../AutoServiceAW-v${{ github.ref_name }}.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: AutoServiceAW-v${{ github.ref_name }}.zip